"""
Code generation: turns a list of recorded Step objects into an executable
Playwright (Python, sync API) script, styled similarly to Playwright's own
`codegen` output. This is the same logic used by the executor internally to
resolve a Playwright Locator for a step (see executor.py:resolve_locator).
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Iterable

from .models import Step


def _py_str(value) -> str:
    if value is None:
        return "None"
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def locator_expr(step: Step) -> str:
    """Return a Python expression (string) that resolves a Playwright Locator."""
    st = step.selectorType
    if st == "testid":
        return f"page.get_by_test_id({_py_str(step.selector)})"
    if st == "id":
        return f"page.locator({_py_str('#' + str(step.selector))})"
    if st == "role":
        role = step.role or "button"
        return f"page.get_by_role({_py_str(role)}, name={_py_str(step.selector)})"
    if st == "css":
        return f"page.locator({_py_str(step.cssEquivalent or step.selector)})"
    if st == "xpath":
        target = step.cssEquivalent or step.selector or ""
        if not str(target).startswith("xpath="):
            target = f"xpath={target}"
        return f"page.locator({_py_str(target)})"
    return f"page.locator({_py_str(step.selector or 'body')})"


def target_locator_expr(step: Step) -> str:
    """Return a Python expression resolving the drag-and-drop target locator."""
    meta = step.meta or {}
    st = meta.get("targetSelectorType") or "css"
    selector = meta.get("targetSelector") or ""
    if st == "testid":
        return f"page.get_by_test_id({_py_str(selector)})"
    if st == "id":
        return f"page.locator({_py_str('#' + str(selector))})"
    if st == "role":
        role = meta.get("targetRole") or "button"
        return f"page.get_by_role({_py_str(role)}, name={_py_str(selector)})"
    if st == "xpath":
        target = meta.get("targetCssEquivalent") or selector or ""
        if not str(target).startswith("xpath="):
            target = f"xpath={target}"
        return f"page.locator({_py_str(target)})"
    return f"page.locator({_py_str(meta.get('targetCssEquivalent') or selector or 'body')})"


def line_for_step(step: Step) -> str:
    action = step.action
    if action == "navigate":
        return f"page.goto({_py_str(step.url)})"
    if action == "click":
        return f"{locator_expr(step)}.click()"
    if action == "upload-click":
        return "# recorded file-picker click; file selection is captured by the upload step"
    if action == "fill":
        return f"{locator_expr(step)}.fill({_py_str(step.value)})"
    if action == "select":
        return f"{locator_expr(step)}.select_option({_py_str(step.value)})"
    if action == "check":
        return f"{locator_expr(step)}.check()"
    if action == "uncheck":
        return f"{locator_expr(step)}.uncheck()"
    if action == "press":
        return f"{locator_expr(step)}.press({_py_str(step.value)})"
    if action == "hover":
        return f"{locator_expr(step)}.hover()"
    if action == "upload":
        return f"{locator_expr(step)}.set_input_files({_py_str(step.value)})  # adjust path(s)"
    if action == "dragdrop":
        return f"{locator_expr(step)}.drag_to({target_locator_expr(step)})"
    if action == "wait":
        timeout = (step.waitFor or {}).get("timeout", 1000)
        return f"page.wait_for_timeout({int(timeout)})"
    if action == "assert-text":
        return f"expect({locator_expr(step)}).to_contain_text({_py_str(step.value)})"
    if action == "assert-visible":
        return f"expect({locator_expr(step)}).to_be_visible()"
    return f"# TODO: unsupported action '{action}'"


def generate_playwright_script(
    steps: Iterable[Step],
    browser: str = "chromium",
    headless: bool = False,
    use_expect: bool = True,
) -> str:
    steps = list(steps)
    lines = []
    lines.append('"""')
    lines.append("Auto-generated by Playwright Recorder & Automation Suite (Desktop App).")
    lines.append(f"Generated: {datetime.now(timezone.utc).isoformat()}")
    lines.append(f"Steps: {len(steps)}")
    lines.append('"""')
    if use_expect:
        lines.append("from playwright.sync_api import sync_playwright, expect")
    else:
        lines.append("from playwright.sync_api import sync_playwright")
    lines.append("")
    lines.append("")
    lines.append("def run():")
    lines.append("    with sync_playwright() as p:")
    lines.append(f"        browser = p.{browser}.launch(headless={headless})")
    lines.append("        context = browser.new_context()")
    lines.append("        page = context.new_page()")
    lines.append("")
    for step in steps:
        ts = datetime.fromtimestamp(step.timestamp / 1000, tz=timezone.utc).isoformat()
        lines.append(f"        # step {step.id} @ {ts} ({step.selectorType})")
        lines.append("        " + line_for_step(step))
        lines.append("        page.wait_for_timeout(150)")
        lines.append("")
    lines.append("        context.close()")
    lines.append("        browser.close()")
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    run()")
    lines.append("")
    return "\n".join(lines)
