/**
 * codegen.js
 * Client-side (JavaScript) mirror of the desktop app's Python code
 * generator, used so the extension can offer an immediate "Download .py"
 * export without a running bridge/desktop app. Produces a Playwright
 * (Python, sync API) script styled like Playwright Codegen output.
 */
(function () {
  function pyStr(value) {
    if (value === null || value === undefined) return 'None';
    return `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  }

  function locatorFor(step) {
    switch (step.selectorType) {
      case 'testid':
        return `page.get_by_test_id(${pyStr(step.selector)})`;
      case 'id':
        return `page.locator(${pyStr('#' + step.selector)})`;
      case 'role':
        return `page.get_by_role(${pyStr(step.role || 'button')}, name=${pyStr(step.selector)})`;
      case 'css':
        return `page.locator(${pyStr(step.cssEquivalent || step.selector)})`;
      case 'xpath':
      default:
        return `page.locator(${pyStr('xpath=' + (step.cssEquivalent || step.selector))})`;
    }
  }

  function targetLocatorFor(step) {
    const meta = step.meta || {};
    const type = meta.targetSelectorType || 'css';
    const selector = meta.targetSelector || '';
    switch (type) {
      case 'testid':
        return `page.get_by_test_id(${pyStr(selector)})`;
      case 'id':
        return `page.locator(${pyStr('#' + selector)})`;
      case 'role':
        return `page.get_by_role(${pyStr(meta.targetRole || 'button')}, name=${pyStr(selector)})`;
      case 'xpath':
        return `page.locator(${pyStr('xpath=' + (meta.targetCssEquivalent || selector))})`;
      case 'css':
      default:
        return `page.locator(${pyStr(meta.targetCssEquivalent || selector)})`;
    }
  }

  function lineFor(step) {
    switch (step.action) {
      case 'navigate':
        return `page.goto(${pyStr(step.url)})`;
      case 'click':
        return `${locatorFor(step)}.click()`;
      case 'upload-click':
        // Clicking a file input can open a native file picker during replay.
        // The recorded `upload` step later performs set_input_files.
        return '# recorded file-picker click; file selection is captured by the upload step';
      case 'fill':
        return `${locatorFor(step)}.fill(${pyStr(step.value)})`;
      case 'select':
        return `${locatorFor(step)}.select_option(${pyStr(step.value)})`;
      case 'check':
        return `${locatorFor(step)}.check()`;
      case 'uncheck':
        return `${locatorFor(step)}.uncheck()`;
      case 'press':
        return `${locatorFor(step)}.press(${pyStr(step.value)})`;
      case 'hover':
        return `${locatorFor(step)}.hover()`;
      case 'upload':
        return `${locatorFor(step)}.set_input_files(${pyStr(step.value)})  # adjust path(s)`;
      case 'wait':
        return `page.wait_for_timeout(${Number((step.waitFor || {}).timeout || 1000)})`;
      case 'assert-text':
        return `expect(${locatorFor(step)}).to_contain_text(${pyStr(step.value)})`;
      case 'assert-visible':
        return `expect(${locatorFor(step)}).to_be_visible()`;
      case 'dragdrop':
        return `${locatorFor(step)}.drag_to(${targetLocatorFor(step)})`;
      default:
        return `# TODO: unsupported action '${step.action}'`;
    }
  }

  function generatePlaywrightScript(steps, options = {}) {
    const browserType = options.browser || 'chromium';
    const headless = options.headless === true ? 'True' : 'False';
    const lines = [];
    lines.push('"""');
    lines.push('Auto-generated by Playwright Recorder & Automation Suite (Chrome Extension).');
    lines.push(`Generated: ${new Date().toISOString()}`);
    lines.push(`Steps: ${steps.length}`);
    lines.push('"""');
    lines.push('from playwright.sync_api import sync_playwright, expect');
    lines.push('');
    lines.push('');
    lines.push('def run():');
    lines.push('    with sync_playwright() as p:');
    lines.push(`        browser = p.${browserType}.launch(headless=${headless})`);
    lines.push('        context = browser.new_context()');
    lines.push('        page = context.new_page()');
    lines.push('');
    for (const step of steps) {
      lines.push(`        # step ${step.id} @ ${new Date(step.timestamp).toISOString()} (${step.selectorType || 'n/a'})`);
      lines.push('        ' + lineFor(step));
      lines.push('        page.wait_for_timeout(150)');
      lines.push('');
    }
    lines.push('        context.close()');
    lines.push('        browser.close()');
    lines.push('');
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push('    run()');
    lines.push('');
    return lines.join('\n');
  }

  // Use globalThis so this module works in a service worker (no window) and
  // in the content-script/page context (window) without throwing.
  const root = typeof globalThis !== 'undefined' ? globalThis : self;
  root.__PW_REC__ = root.__PW_REC__ || {};
  root.__PW_REC__.codegen = { generatePlaywrightScript };
  root.__PW_CODEGEN__ = { generatePlaywrightScript };
})();
