"""
Auto-generated by Playwright Recorder & Automation Suite (Desktop App).
Generated: 2026-09-06T17:51:01.656687+00:00
Steps: 9
"""
from playwright.sync_api import sync_playwright, expect


def run():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()

        # step b3b9c9b0-6f1a-4a9e-9c2e-6b6f1a2b0001 @ 2024-11-21T14:40:00+00:00 (None)
        page.goto("https://demo-shop.example.com/login")
        page.wait_for_timeout(150)

        # step b3b9c9b0-6f1a-4a9e-9c2e-6b6f1a2b0002 @ 2024-11-21T14:40:02.500000+00:00 (testid)
        page.get_by_test_id("email").fill("jane.doe@example.com")
        page.wait_for_timeout(150)

        # step b3b9c9b0-6f1a-4a9e-9c2e-6b6f1a2b0003 @ 2024-11-21T14:40:04.100000+00:00 (testid)
        page.get_by_test_id("password").fill("Sup3rSecret!")
        page.wait_for_timeout(150)

        # step b3b9c9b0-6f1a-4a9e-9c2e-6b6f1a2b0004 @ 2024-11-21T14:40:04.600000+00:00 (testid)
        page.get_by_test_id("password").press("Enter")
        page.wait_for_timeout(150)

        # step b3b9c9b0-6f1a-4a9e-9c2e-6b6f1a2b0005 @ 2024-11-21T14:40:06+00:00 (None)
        page.goto("https://demo-shop.example.com/dashboard")
        page.wait_for_timeout(150)

        # step b3b9c9b0-6f1a-4a9e-9c2e-6b6f1a2b0006 @ 2024-11-21T14:40:08.200000+00:00 (role)
        page.get_by_role("button", name="Add to cart").click()
        page.wait_for_timeout(150)

        # step b3b9c9b0-6f1a-4a9e-9c2e-6b6f1a2b0007 @ 2024-11-21T14:40:09.900000+00:00 (css)
        page.locator("#shipping-method").select_option("express")
        page.wait_for_timeout(150)

        # step b3b9c9b0-6f1a-4a9e-9c2e-6b6f1a2b0008 @ 2024-11-21T14:40:11+00:00 (testid)
        page.get_by_test_id("terms-checkbox").check()
        page.wait_for_timeout(150)

        # step b3b9c9b0-6f1a-4a9e-9c2e-6b6f1a2b0009 @ 2024-11-21T14:40:13.500000+00:00 (role)
        page.get_by_role("button", name="Checkout").click()
        page.wait_for_timeout(150)

        context.close()
        browser.close()


if __name__ == "__main__":
    run()
